apiVersion: batch/v1
kind: Job
metadata:
  name: s3www-app-init
  labels:
    app: s3www-app
    chart: s3www-app-0.1.0
    release: s3www-app
    heritage: Helm
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    metadata:
      labels:
        app: s3www-app
        release: s3www-app
        job-name: s3www-app-init
    spec:
      restartPolicy: OnFailure
      serviceAccountName: s3www-app-serviceaccount
      containers:
      - name: init
        image: "alpine:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: MINIO_ENDPOINT
          value: {{ .Values.config.minioEndpoint | quote }}
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3www-app-minio-secret
              key: access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3www-app-minio-secret
              key: secret-key
        - name: BUCKET_NAME
          value: {{ .Values.config.bucketName | quote }}
        - name: FILE_URL
          value: {{ .Values.init.fileUrl | quote }}
        - name: FILE_NAME
          value: {{ .Values.init.fileName | quote }}
        command:
        - /bin/sh
        - -c
        - |
          # Install MinIO client
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          
          # Configure MinIO client
          ./mc alias set myminio $MINIO_ENDPOINT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          
          # Create bucket if it doesn't exist
          ./mc mb myminio/$BUCKET_NAME || true
          
          # Download file if URL is provided
          if [ -n "$FILE_URL" ] && [ "$FILE_URL" != "null" ]; then
            echo "Downloading file from $FILE_URL..."
            wget -O /tmp/$FILE_NAME $FILE_URL
            
            # Upload file to MinIO
            echo "Uploading $FILE_NAME to MinIO bucket $BUCKET_NAME..."
            ./mc cp /tmp/$FILE_NAME myminio/$BUCKET_NAME/
            
            echo "File upload completed successfully!"
          else
            echo "No file URL provided, skipping file download and upload"
          fi
          
          # List files in bucket for verification
          echo "Files in bucket $BUCKET_NAME:"
          ./mc ls myminio/$BUCKET_NAME/ 