apiVersion: v1
kind: Secret
metadata:
  name: s3www-app-minio-secret
  labels:
    app: s3www-app
type: Opaque
data:
  access-key: {{ .Values.config.minioAccessKey | b64enc }}
  secret-key: {{ .Values.config.minioSecretKey | b64enc }} 