apiVersion: v1
kind: Service
metadata:
  name: s3www-app-service
  labels:
    app: s3www-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: s3www-app 